#Fusion IHC Server
#Fri Jul 26 20:16:23 UTC 2019
FUSION_JAVA_HOME_OVERRIDE=''
FUSION_SERVER_GROUP='hdfs'
FUSION_SERVER_USER='hdfs'
IHC_MEM_HIGH=64
IHC_MEM_LOW=64
FUSION_PREFIX='/opt/wandisco'
FUSION_JAVA_HOME_FALLBACK='/usr/java/jdk1.8.0_131'
export MAPR_IMPERSONATION_ENABLED='true'